# $ python scripts/main.py fit -c configs/train.yaml --ckpt_path 'path'
# lightning.pytorch==2.1.2
seed_everything: 2894872274
trainer:
  accelerator: auto
  strategy: auto
  devices: 1
  num_nodes: 1
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      save_dir: ./lightning_logs/
      offline: false
      project: patch-vsr-net
      log_model: True
      prefix: ''
      group: '4x96@CRF30+LL'
  callbacks:
    - class_path: ImageLog
    - class_path: ModelCheckpoint
      init_args:
        save_top_k: 10
        monitor: epoch
        mode: max
        every_n_epochs: 10
  fast_dev_run: false
  max_epochs: 100
  max_steps: -1
  overfit_batches: 0.0
  check_val_every_n_epoch: 1
  accumulate_grad_batches: 1
  inference_mode: true
  use_distributed_sampler: true
  detect_anomaly: false
  barebones: false
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0

model:
  class_path: models.vsr_with_ll_single_module.VSRSingle
  init_args:
    generator:
      class_path: archs.patch_vsr_net.PatchVSRNet
      init_args:
        scale_factor: &UPSCALE_FACTOR 4
        residual: true
        align_net:
          class_path: archs.align_net.AlignNet
          init_args:
            in_channels: 3
            top_k: 1
            block_size: 16
            stride: 8
    gen_lr: 5e-4
    losses:
      pixel_crit:
        type: CB
        weight: 1
        reduction: mean
      align_crit:
        type: CB
        weight: 1
        reduction: mean
      feature_crit:
        type: LPIPS
        weight: 0.2
        net: alex

data:
  hr_path: /home/DATASETS/BVI_DVC/frames_HQ/
  lr_path: /home/DATASETS/BVI_DVC/frames/frames_CRF_30
  hr_path_filter: '1088'
  lr_path_filter: '544'
  validation_classes:
    - AmericanFootballS3Harmonics
    - BasketballS3YonseiUniversity
    - CityStreetS7IRIS
    - SquareS2IRIS
    - StreetDancerS5IRIS
  patch_size: 96
  tempo_extent: 7
  augment: true
  dataset_upscale_factor: *UPSCALE_FACTOR
  batch_size: 16
